name: Save Daily Portfolio

on:
  schedule:
    - cron: '10 10 * * 1-5'   # 3:40 PM IST (10:10 UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch sheet and calculate value
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vSoFliPrj40L2ujuP3ZSGbnHD4IZ27UY5D1TEjpEvBXvn1SewQdQmNQaYVyaZoQ_sGgHkL3NIpfkpbq/pub?gid=0&single=true&output=csv" -o sheet.csv
          
          total=0
          while IFS=, read -r Symbol Qty BuyPrice ClosePrice
          do
            if [ "$Qty" != "Qty" ]; then
              value=$(echo "$Qty * $ClosePrice" | bc)
              total=$(echo "$total + $value" | bc)
            fi
          done < sheet.csv

          today=$(date +'%Y-%m-%d')
          echo "$today,$total" >> portfolio_history.csv

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add portfolio_history.csv
          git commit -m "Daily portfolio update"
          git push
